### ISSUE TITLE
KeyError: 'Lat'

### ISSUE THREAD

**Issue by jakimowb** [Themapworkshop/COVID19TRACKER#4]
Each time add a covid19tracker layer I get the following pandas error:
````
2020-04-20T14:12:44     WARNING    Traceback (most recent call last):
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\pandas\core\indexes\base.py", line 2646, in get_loc
              return self._engine.get_loc(key)
              File "pandas\_libs\index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
              File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
              File "pandas\_libs\hashtable_class_helper.pxi", line 1618, in pandas._libs.hashtable.PyObjectHashTable.get_item
              File "pandas\_libs\hashtable_class_helper.pxi", line 1626, in pandas._libs.hashtable.PyObjectHashTable.get_item
             KeyError: 'Lat'
             During handling of the above exception, another exception occurred:
             Traceback (most recent call last):
              File "C:/Users/geo_beja/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\covid19_tracker\Covid19_Tracker.py", line 388, in stat
              for i in range(len(f['Lat'])):
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\pandas\core\frame.py", line 2800, in __getitem__
              indexer = self.columns.get_loc(key)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\pandas\core\indexes\base.py", line 2648, in get_loc
              return self._engine.get_loc(self._maybe_cast_indexer(key))
              File "pandas\_libs\index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
              File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
              File "pandas\_libs\hashtable_class_helper.pxi", line 1618, in pandas._libs.hashtable.PyObjectHashTable.get_item
              File "pandas\_libs\hashtable_class_helper.pxi", line 1626, in pandas._libs.hashtable.PyObjectHashTable.get_item
             KeyError: 'Lat'
````
# Version

QGIS version | 3.12.0-București | QGIS code revision | cd141490ec
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Windows 10 (10.0)
Active python plugins | enmapboxplugin; localmaxfilter; timeseriesviewerplugin; processing; covid19_tracker

**Comment by dershow** [comment]
I'm seeing the same error while trying to run QGIS 3.14 on Mac OS 10.15.6
